name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [ "main" ]     # Adjust if your default branch is not 'main'
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.115.4"
          extended: true

      - name: Build the site
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-pages     # Must match in 'deploy' job
          path: public         # Where Hugo outputs files

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact-name: hugo-pages
